server:
  port: 19872

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

spring:
  application:
    name: eureka-client
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

  datasource:
      platform: postgres
      url: jdbc:postgresql://77.37.134.139:5522/ravilich
      username: ravilich
      password: 234
      driverClassName: org.postgresql.Driver
